### ISSUE TITLE
could this interpret the return type of a function call?

### ISSUE THREAD

**Issue by tmc** [koron/iferr#3]
It would be interesting if a function call with an error type in it's returned types could be used in generating the output.

For example:
```go
func a(w io.Writer) ([]byte, error) {
    w.Write([]byte("foo"))
}
```
if run at the w.Write call it could produce:
```go
func a(w io.Writer) ([]byte, error) {
    if _, err := w.Write([]byte("foo")); err != nil {
        return nil, err
    }
}
```

**Comment by koron** [comment]
no, with current method.
currently, iferr uses `go/ast` and parses a target file only.

to generate such like codes, we should read other files which define type of `w` and determine signature of `Write` method, and should use `reflect` too.
it will be big change, so i don't want to do it for now.

**Comment by tmc** [comment]
perhaps guru describe could be used for this

**Comment by tmc** [comment]
could just hack it and support the one-return case

**Comment by koron** [comment]
i want keep iferr as simple as possible.
